//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintsEntry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Prm_Fct_Complaints
    {
        public int coID { get; set; }
        public string coCarelineRef { get; set; }
        public string coExtractDate { get; set; }
        public string coReference { get; set; }
        public string coType { get; set; }
        public string coSource { get; set; }
        public string coRetailer { get; set; }
        public Nullable<System.DateTime> coDateEntered { get; set; }
        public Nullable<System.DateTime> coBestBeforeDate { get; set; }
        public string coRetailerStoreRef { get; set; }
        public string coRetailerHORef { get; set; }
        public string coProductionCode { get; set; }
        public string coJulianCode { get; set; }
        public string coAdditionalDetail { get; set; }
        public string coComplaintCategory { get; set; }
        public string coElement { get; set; }
        public string coSubElement { get; set; }
        public string coConsumerFault { get; set; }
        public string coConfirmedAS { get; set; }
        public string coDepartmentCode { get; set; }
        public string coCurrencySymbol { get; set; }
        public Nullable<decimal> coTotalReimbursement { get; set; }
        public string coPremierCSNCode { get; set; }
        public string coManufacturingLocation { get; set; }
        public string coDoughCode { get; set; }
        public string coBakery { get; set; }
        public string coRetailerAdmin { get; set; }
    }
}
